#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 24 11:35:47 2021

@author: zmg
"""


class Student:
    def __init__(self, name, results):
        self.name = name
        for key, value in results.items():
            # Sets the attribute of the 'subject' to
            # the corresponding subject mark.
            # For example: a.'Chemistry' = 75
            setattr(self, key, value)

    def update_mark(self, subject, mark):
        self.subject = mark


subjects = ["Physics", "Chemistry", "Biology"]

a = Student("Amit", {key: value for (key, value) in zip(subjects, [73, 81, 90])})
